services:
  dogapi:
    image: ${DOCKER_REGISTRY-}dogapi
    container_name: dogapi-container
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      Serilog__WriteTo__0__Args__serverUrl: "http://seq:5341"
    ports:
      - 5000:5000
    build:
      context: ./src/DogApi
      dockerfile: Dockerfile
    depends_on:
      - seq
  seq: 
    image: datalust/seq:latest
    container_name: seq-container
    environment:
      ACCEPT_EULA: Y
    ports: 
      - 5341:80
    volumes:
      - seq_data:/data
volumes:
  seq_data:
